gpu_list:
    - 0
data:
  split_path: /vols/hyperk/users/nprouse/WCTE/ML/wcsim_wcte_pgun_3M_e-_3M_mu-_3M_gamma_3M_pi+/index_lists/wcsim_wcte_pgun_3M_e-_3M_mu-_3M_gamma_3M_pi+_2class_emu_ALL.npz
  dataset:
    h5file: /vols/hyperk/users/nprouse/WCTE/ML/wcsim_wcte_pgun_3M_e-_3M_mu-_3M_gamma_3M_pi+/h5/wcsim_wcte_pgun_3M_e-_3M_mu-_3M_gamma_3M_pi+_0to1GeV.h5
    mpmt_positions_file: /vols/t2k/WCTE/ml_2024/WCTE_mPMT_image_positions.npz
    channels: ['charge', 'time', 'mpmt_position']
    channel_scaling:
      mpmt_position:
        - 0
        - 100
    geometry_file: /vols/t2k/WCTE/ml_2024/wcte_full_geo_v1.2.npz
model:
  num_input_channels: 41
  num_output_channels: 2
tasks:
  evaluate:
    data_loaders:
      test:
        batch_size: 1024
  restore_state:
    weight_file: /home/hep/kj4718/WatChMaL/outputs/2025-02-10/23-05-15.440399/outputs/ClassifierEngine_ResNet_BEST.pth
engine:
  label_set:
  - 1
  - 2
hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S.%f}
defaults:
    - resnet_test
    - override model: resnet50
    - _self_