# ...existing code...
defaults:
    - reg_train
    - override model: resnet50
    - _self_
gpu_list:
    - 0
data:
  split_path: /rds/general/user/kj4718/home/ML_2025/old_geometry/split_paths/wcsim_wcte_pgun_3M_e-_3M_mu-_3M_gamma_3M_pi+_1class_e-_FC.npz
  dataset:
    transforms: [double_cover]
    default_transformation: False
    use_new_mpmt_convention: True
    h5file: /rds/general/user/kj4718/home/ML_2025/old_geometry/h5_files/wcsim_wcte_pgun_3M_e-_3M_mu-_3M_gamma_3M_pi+_0to1GeV.h5
    mpmt_positions_file: /rds/general/user/kj4718/home/ML_2025/old_geometry/mpmt_pos_files/WCTE_mPMT_image_positions.npz
    geometry_file: /rds/general/user/kj4718/home/ML_2025/old_geometry/geometries/wcte_full_geo_v1.2.npz
    channels:
      - charge
      - time
      - mpmt_position
    channel_scale_offset:
      time: 0
      charge: 0
      mpmt_position: 0
    channel_scale_factor:
      time: 10
      mpmt_position: 100
tasks:
  train:
    data_loaders:
      train:
        batch_size: 1024
        pre_transforms: []
      validation:
        batch_size: 2048
    num_val_batches: 16
    val_interval: 20
    optimizers:
      lr: 0.02
  evaluate:
    data_loaders:
      test:
        batch_size: 2048
engine:
  target_key:
    - directions
model:
  _target_: watchmal.model.resnet.resnet50
  conv_pad_mode: circular
  num_output_channels: 3
hydra:
  run:
    dir: /rds/general/user/kj4718/home/ML_2025/old_geometry/outputs/regression/dir/${now:%Y-%m-%d_%H-%M-%S}