data:
  split_path: /vols/hyperk/WCTE/ML_2025/cds_geometry/split_paths/cds_split_path_emu_ALL.npz
  dataset:
    h5file: /vols/hyperk/WCTE/ML_2025/cds_geometry/h5_files/wcte_CDS_pgun_e-_3M_mu-_3M_0to1GeV_fixedFC.h5
    mpmt_positions_file: /vols/hyperk/WCTE/ML_2025/cds_geometry/mpmt_pos_files/WCTE_mPMT_image_positions_v3.npz
    geometry_file: /vols/hyperk/WCTE/ML_2025/cds_geometry/geometries/WCTE_geometry_v1.12.21.npz
    channels:
      - mpmt_position
      - charge
      - time
    channel_scale_offset:
      time: 0
      charge: 0
      mpmt_position: 0
    channel_scale_factor:
      time: 10
      charge: 1
      mpmt_position: 100
    use_new_mpmt_convention: true
engine:
  label_set:
    - 1
    - 2
model:
  num_input_channels: 41
  num_output_channels: 2
tasks:
  train:
   optimizers:
     lr: 0.02
   epochs: 20
   val_interval: 20
   num_val_batches: 16
   data_loaders:
    train:
      batch_size: 1024
      pre_transforms:
        - random_reflections 
    validation:
      batch_size: 2048
  evaluate:
    data_loaders:
      test:
        batch_size: 2048
gpu_list:
  - 0
defaults:
    - resnet_train
    - override model: resnet50
    - _self_
